---
title: '225A Workshop 2: RStudio and Tidyverse'
author: "Nikhita Kirthivasan"
date: "2023-10-12"
output: html_document
---
#Weather Data Analysis


```{r load_packages}
library (tidyverse)
```

```{r Read in Data}
sf_Weather <- read.csv("../raw_data/sf_weather_2023.csv")
head(sf_Weather)
colnames(sf_Weather)
```

```{r Subset the data}
sf_Weather %>% 
  select(DATE)
date <- sf_Weather %>% 
  select(DATE)
```

```{r Subset the data and split out data}
sf_Weather_temps <- sf_Weather %>% 
  select(c(DATE,TMAX,TMIN)) %>% 
  na.omit() %>% 
  separate(DATE, c("YEAR", "MONTH","DAY"), sep="-", remove=F) %>% 
  filter(YEAR == "2021") %>%
  mutate(TAVG = ((TMAX+TMIN)/2)) %>% 
  group_by(MONTH) %>% 
  summarise(MAX_MO_TEMP = max(TAVG))

sf_Weather_temps
```

```{r Plotting out data}
plot(sf_Weather_temps)

```

```{r Make a function to subset data}
yearly_subsetter <- function(year){
  year_subset <- sf_Weather %>% 
    select(c(DATE,TMAX,TMIN)) %>% 
    na.omit() %>% 
    separate(DATE, c("YEAR", "MONTH","DAY"), sep="-", remove=F) %>% 
  filter(YEAR == year) %>%
  mutate(TAVG = ((TMAX+TMIN)/2)) %>% 
  group_by(MONTH) %>% 
  summarise(MAX_MO_TEMP = max(TAVG))
    
  year_subset
}

```

```{r Apply function to date}
year <- "2010"

plot(yearly_subsetter(year), main = year)
```

```{r Inspect several years at once with a loop, fig.width=6, fig.height=4}
for (year in c("1970", "1980", "1990", "2000")){
  plot(yearly_subsetter(year), main = year)
}

```

